# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none
pr: none

variables:
  vmImageNameDefault: 'ubuntu-latest'
  enviroment: uat

stages:
  - stage: UAT
    displayName: UAT
    jobs:
    - deployment: createNamespace
      displayName: Create Namespace
      pool:
        name: pagopa-agent-pool-uat
      environment: 'uat'
      strategy:
        runOnce:
          deploy:
            steps:
              - download: none
#              - task: DownloadPipelineArtifact@2
#                inputs:
#                  buildType: 'current'
#                  artifactName: 'manifests'
#                  targetPath: '$(Pipeline.Workspace)/manifests'
              - task: KubernetesManifest@0
                displayName: 'Create Namespace'
                inputs:
                  namespace: tkm-uat
                  action: deploy
                  kubernetesServiceConnection: 'u87-aks-pci-uat-self-connection-tkm'
                  manifests: |
                    refs/heads/PM-805-pipeline-uat/manifests/namespace-$(enviroment).yml
  - stage: Pre_Deploy
    displayName: 'Pre-Deploy'
    jobs:
    - job: Pre_Deploy
      displayName: 'Pre-Deploy'
      pool:
        vmImage: $(vmImageNameDefault)
      steps:
        - task: DownloadSecureFile@1
          displayName: 'download tkmmsacquirermanager.yaml'
          name: tkmmsacquirermanager
          inputs:
            secureFile: 'tkmmsacquirermanager-$(enviroment).yaml'
            retryCount: '2'
        - task: Kubernetes@1
          displayName: 'apply tkmmsacquirermanager.yaml'
          inputs:
            connectionType: Azure Resource Manager
            azureSubscriptionEndpoint: 'U87-PagoPa-PCI-uat(e7feb90c-fcc2-40a2-ba56-d68ec301c6c0)'
            azureResourceGroup: 'U87-AKS-pci-uat'
            kubernetesCluster: 'U87-AKS-pci-uat'
            command: apply
            useConfigurationFile: true
            configuration: $(tkmmsacquirermanager.secureFilePath)
