SERVER_PORT: 8745
AZURE_KEYVAULT_PROFILE: local
KAFKA_APPENDER_SECURITY_PROTOCOL: PLAINTEXT
KAFKA_APPENDER_TOPIC: tkm-log
AZURE_STORAGE_ENDPOINT: https://127.0.0.1:8125/devstoreaccount1
VISA_URL_ACQUIRER: https://sandbox.api.visa.com/v1/binRangeDetails
DB_SERVER: localhost:5000/tkm_acquirer_manager
LOGGING_LEVEL: DEBUG
SFTP_SIA_HOSTNAME: localhost
SFTP_SIA_PORT: 2222
SFTP_SIA_USER: local
SFTP_SIA_FOLDER: upload
KAFKA_READ_QUEUE_TOPIC: tkm-read-token-par-pan
KAFKA_SERVERS: localhost:9092
KAFKA_SECURITY_PROTOCOL: PLAINTEXT
CARD_MANAGER_URL: http://localhost
##BLOB CONTAINER
BLOB_STORAGE_BIN_HASH_CONTAINER: tkm-acquirer-data
BLOB_STORAGE_ACQUIRER_CONFIG_CONTAINER: tkm-acquirer-config
##CRON CONFIG
BIN_RANGE_RETRIEVAL_CRON: '-'
BIN_RANGE_GEN_CRON: 0/10 * * * * ?
HTOKEN_HPAN_COPY_CRON: '-'
BATCH_ACQUIRER_RESULT_CRON: '-'
KNOWN_HASHES_GEN_CRON: '-'
BATCH_MAX_THREAD: 6
## NEED SET
AZURE_KEYVAULT_URI: ${AZURE_KEYVAULT_URI}
AZURE_KEYVAULT_CLIENT_ID: ${AZURE_KEYVAULT_CLIENT_ID}
AZURE_KEYVAULT_CLIENT_KEY: ${AZURE_KEYVAULT_CLIENT_ID}
AZURE_KEYVAULT_TENANT_ID: ${AZURE_KEYVAULT_CLIENT_ID}

##Use only one CPU -XX:ActiveProcessorCount=1