CREATE TABLE BIN_RANGE (
    ID SERIAL PRIMARY KEY,
    CIRCUIT VARCHAR(32) NOT NULL,
    MIN VARCHAR(30) NOT NULL,
    MAX VARCHAR(30) NOT NULL,
    INSERT_DATE TIMESTAMP NOT NULL
);

CREATE TABLE BATCH_RESULT (
    ID SERIAL PRIMARY KEY,
    TARGET_BATCH VARCHAR(32) NOT NULL,
    RUN_DATE TIMESTAMP NOT NULL,
    RUN_OUTCOME BOOLEAN NOT NULL,
    DETAILS VARCHAR(10000) NOT NULL,
    RUN_DURATION_MILLIS INTEGER NOT NULL,
    EXECUTION_TRACE_ID VARCHAR(16) NOT NULL
);

CREATE TABLE shedlock (
  name VARCHAR(64) PRIMARY KEY,
  lock_until TIMESTAMP(3),
  locked_at TIMESTAMP(3),
  locked_by VARCHAR(255)
);

CREATE TABLE hash_offset (
  id SERIAL PRIMARY KEY,
  last_hpan_offset INTEGER,
  last_htoken_offset INTEGER,
  last_hashes_file_filename VARCHAR(64),
  last_hashes_file_row_count INTEGER,
  last_hashes_file_index INTEGER
);