apiVersion: apps/v1
kind: Deployment
metadata:
  name: tkmmsacquirermanageruat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tkmmsacquirermanageruat
  template:
    metadata:
      labels:
        app: tkmmsacquirermanageruat
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
    spec:
      nodeSelector:
        tkm-uat: 'true'
      hostAliases:
        - ip: "10.70.73.228"
          hostnames:
            - "tkm-pgsql-pci-uat.postgres.database.azure.com"
        - ip: "10.70.73.37"
          hostnames:
            - "u87-evh-pci-uat.servicebus.windows.net"
        - ip: "10.70.73.38"
          hostnames:
            - "tkmstorageblobuatpci.blob.core.windows.net"
        - ip: "10.230.9.5"
          hostnames:
            - "api.uat.platform.pagopa.it"
      volumes:
        - name: secrets-store-inline-acquirer-manager
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: tkm-acquirer-manager-spc-uat
            nodePublishSecretRef:
              name: tkm-acquirer-manager-kv-store-creds-uat
      containers:
        - name: tkmmsacquirermanageruat
          image: cstaruatregistry.azurecr.io/tkmmsacquirermanager
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 4Gi
              cpu: 500m
            limits:
              memory: 4Gi
              cpu: 1000m
          volumeMounts:
            - name: secrets-store-inline-acquirer-manager
              mountPath: /mnt/secrets-store
              readOnly: true
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
          env:
            - name: TZ
              valueFrom:
                secretKeyRef:
                  key: TZ
                  name: jvm
            - name: KAFKA_APPENDER_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  key: KAFKA_APPENDER_BOOTSTRAP_SERVERS
                  name: kafka-log-configuration
            - name: ENABLE_FILE_APPENDER
              valueFrom:
                secretKeyRef:
                  key: ENABLE_FILE_APPENDER
                  name: kafka-log-configuration
            - name: ENABLE_KAFKA_APPENDER
              valueFrom:
                secretKeyRef:
                  key: ENABLE_KAFKA_APPENDER
                  name: kafka-log-configuration
            - name: LOG_FILE
              valueFrom:
                secretKeyRef:
                  key: LOG_FILE
                  name: kafka-log-configuration
            - name: KAFKA_APPENDER_TOPIC
              valueFrom:
                secretKeyRef:
                  key: KAFKA_APPENDER_TOPIC
                  name: kafka-log-configuration
            - name: AZURE_KEYVAULT_PROFILE
              valueFrom:
                secretKeyRef:
                  key: AZURE_KEYVAULT_PROFILE
                  name: keyvault-connection-informations
            - name: AZURE_KEYVAULT_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: AZURE_KEYVAULT_CLIENT_ID
                  name: keyvault-connection-informations
            - name: AZURE_KEYVAULT_CLIENT_KEY
              valueFrom:
                secretKeyRef:
                  key: AZURE_KEYVAULT_CLIENT_KEY
                  name: keyvault-connection-informations
            - name: AZURE_KEYVAULT_TENANT_ID
              valueFrom:
                secretKeyRef:
                  key: AZURE_KEYVAULT_TENANT_ID
                  name: keyvault-connection-informations
            - name: AZURE_KEYVAULT_URI
              valueFrom:
                secretKeyRef:
                  key: AZURE_KEYVAULT_URI
                  name: keyvault-connection-informations
            - name: AZURE_STORAGE_ENDPOINT
              valueFrom:
                secretKeyRef:
                  key: AZURE_STORAGE_ENDPOINT
                  name: tkmmsacquirermanager
            - name: BATCH_ACQUIRER_RESULT_CRON
              valueFrom:
                secretKeyRef:
                  key: BATCH_ACQUIRER_RESULT_CRON
                  name: tkmmsacquirermanager
            - name: BIN_RANGE_GEN_CRON
              valueFrom:
                secretKeyRef:
                  key: BIN_RANGE_GEN_CRON
                  name: tkmmsacquirermanager
            - name: BIN_RANGE_RETRIEVAL_CRON
              valueFrom:
                secretKeyRef:
                  key: BIN_RANGE_RETRIEVAL_CRON
                  name: tkmmsacquirermanager
            - name: BLOB_STORAGE_ACQUIRER_CONFIG_CONTAINER
              valueFrom:
                secretKeyRef:
                  key: BLOB_STORAGE_ACQUIRER_CONFIG_CONTAINER
                  name: tkmmsacquirermanager
            - name: BLOB_STORAGE_BIN_HASH_CONTAINER
              valueFrom:
                secretKeyRef:
                  key: BLOB_STORAGE_BIN_HASH_CONTAINER
                  name: tkmmsacquirermanager
            - name: CARD_MANAGER_URL
              valueFrom:
                secretKeyRef:
                  key: CARD_MANAGER_URL
                  name: tkmmsacquirermanager
            - name: DB_SERVER
              valueFrom:
                secretKeyRef:
                  key: DB_SERVER
                  name: tkmmsacquirermanager
            - name: KAFKA_GROUP_ID
              valueFrom:
                secretKeyRef:
                  key: KAFKA_GROUP_ID
                  name: tkmmsacquirermanager
            - name: KAFKA_READ_QUEUE_TOPIC
              valueFrom:
                secretKeyRef:
                  key: KAFKA_READ_QUEUE_TOPIC
                  name: tkmmsacquirermanager
            - name: KAFKA_SERVERS
              valueFrom:
                secretKeyRef:
                  key: KAFKA_SERVERS
                  name: tkmmsacquirermanager
            - name: KNOWN_HASHES_COPY_CRON
              valueFrom:
                secretKeyRef:
                  key: KNOWN_HASHES_COPY_CRON
                  name: tkmmsacquirermanager
            - name: KNOWN_HASHES_GEN_CRON
              valueFrom:
                secretKeyRef:
                  key: KNOWN_HASHES_GEN_CRON
                  name: tkmmsacquirermanager
            - name: VISA_URL_ACQUIRER
              valueFrom:
                secretKeyRef:
                  key: VISA_URL_ACQUIRER
                  name: tkmmsacquirermanager
            - name: BLOB_STORAGE_ACQUIRER_CONTAINER
              valueFrom:
                secretKeyRef:
                  key: BLOB_STORAGE_ACQUIRER_CONTAINER
                  name: tkmmsacquirermanager
            - name: ACQUIRER_FILE_UPLOAD_CHUNK_SIZE_MB
              valueFrom:
                secretKeyRef:
                  key: ACQUIRER_FILE_UPLOAD_CHUNK_SIZE_MB
                  name: tkmmsacquirermanager
            - name: ACQUIRER_FILE_UPLOAD_MAX_CONCURRENCY
              valueFrom:
                secretKeyRef:
                  key: ACQUIRER_FILE_UPLOAD_MAX_CONCURRENCY
                  name: tkmmsacquirermanager
            - name: ACQUIRER_FILE_UPLOAD_TIME_LIMIT_MINUTES
              valueFrom:
                secretKeyRef:
                  key: ACQUIRER_FILE_UPLOAD_TIME_LIMIT_MINUTES
                  name: tkmmsacquirermanager
            - name: ACQUIRER_FILE_DAYS_TO_LIVE
              valueFrom:
                secretKeyRef:
                  key: ACQUIRER_FILE_DAYS_TO_LIVE
                  name: tkmmsacquirermanager
            - name: APPLICATIONINSIGHTS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  key: APPLICATIONINSIGHTS_CONNECTION_STRING
                  name: applicationinsights
            - name: APPLICATIONINSIGHTS_ROLE_NAME
              value: tkmmsacquirermanageruat
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 30
          imagePullPolicy: Always
